server:
  port: 8083
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/service-passenger-user?chracterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 12345678

